### ISSUE TITLE
[Bug]: [v0.1.0] [example/single_operation/get.go]The type of column c2 in the SQL statement does not match the type in the insert operation

### ISSUE THREAD

**Issue by wayyoungboy** [oceanbase/obkv-table-client-go#80]
**Describe the bug**

The type of column c2 in the SQL statement does not match the type in the insert operation

**Environment**

- OS Version and CPU Arch(`uname -a`):
  any
- Component Version:
  
v0.1.0
**Fast Reproduce Steps(Required)**

- execute the sql of CREATE TABLE
- go run example/single_operation/get.go

**Expected behavior**

pass

**Actual Behavior**

panic: execute insert, tableName:test, rowKey:[column{name:c1, value:1}], mutateColumns:[column{name:c2, value:2}]: errCode:-4001, errCodeName:ObObjTypeError, errMsg:Column type not match., server:xxxxxx, trace:xxxx, tableName:test

**Additional context**

**Comment by namewxt1220** [comment]
table column type not match, thank you for asking the question.
